// Note: Autogenerated

#ifndef _PINCONFIG_H
#define _PINCONFIG_H

#define PIN_BTN_A 2
#define PIN_GPIO_2 3
#define PIN_SDA_1 3
#define PIN_GPIO_3 4
#define PIN_SCL_1 4
#define PIN_GPIO_14 5
#define PIN_TXD_0 5
#define PIN_BTN_SELECT 5
#define PIN_GPIO_26 6
#define PIN_BTN_DOWN 6
#define PIN_GPIO_21 7
#define PIN_PCM_DOUT 7
#define PIN_BTN_LEFT 7
#define PIN_GPIO_4 8
#define PIN_GPCLK_0 8
#define PIN_GPIO_20 11
#define PIN_PCM_DIN 11
#define PIN_BTN_RIGHT 11
#define PIN_GPIO_5 12
#define PIN_GPIO_13 13
#define PIN_PWM_1 13
#define PIN_GPIO_19 14
#define PIN_PCM_FS 14
#define PIN_BTN_UP 14
#define PIN_GPIO_16 15
#define PIN_GPIO_6 16
#define PIN_GPIO_12 17
#define PIN_PWM_0 17
#define PIN_ID_SD 18
#define PIN_I2C_ID 18
#define PIN_EEPROM 18
#define PIN_ID_SC 27
#define PIN_I2C_ID 27
#define PIN_EEPROM 27
#define PIN_GPIO_7 28
#define PIN_SPI_0_CE1 28
#define PIN_GPIO_11 29
#define PIN_SPI_0_SCLK 29
#define PIN_GPIO_8 30
#define PIN_SPI_0_CE0 30
#define PIN_GPIO_9 31
#define PIN_SPI_0_MISO 31
#define PIN_GPIO_25 32
#define PIN_GPIO_23 34
#define PIN_GPIO_10 35
#define PIN_SPI_0_MOSI 35
#define PIN_GPIO_24 36
#define PIN_GPIO_25 37
#define PIN_LED_DI 37
#define PIN_GPIO_27 38
#define PIN_GPIO_17 39
#define PIN_GPIO_18 40
#define PIN_PCM_CLK 40
#define PIN_GPIO_15 41
#define PIN_RXD_0 41


#endif
