M48
; DRILL file {KiCad (6.0.6)} date Wed 20 Jul 2022 01:38:39 PM AEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-20T13:38:39+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X0.6431Y-0.2293
X0.8707Y-0.2293
T2
X0.9649Y-1.285
X1.0049Y-1.585
X1.0449Y-1.285
T0
M30
